### ISSUE TITLE
c-loader-status: Add an option to make the progress bar positioned absolute, allowing it to overlap content in tight contexts 

### ISSUE THREAD

**Issue by ascott18** [IntelliTect/Coalesce#343]
There are cases (e.g. table-like structures where every row has a c-loader-status) where it is desirable to show a c-loader-status for progress, but where having content jumps are undesirable (disabling the progress placeholder), and taking up padding for the progress placeholder induces extra undesirable padding. An easy option to enable this CSS per c-loader-status would be nice:

``` css
  .c-loader-status--progress-group {
    // Make the progress bar on c-loader-status overlap
    // so it doesn't add extra whitespace to the top of the row.
    position: absolute !important;
    width: 100%;
  }
```
